safe: true
#doesnt work on github
#source: ./src
source: ./
#have to build to _site so the old build doesnt get copied over
#destination: ./site
destination: ./_site
lsi: false
# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount

# configuration required for some pages

domain: www.digimulti.com
title: Digimulti
author: Ben Pettit
email: ben.pettit@digimulti.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
    account: UA-27422700-1

github:
    username: pellet

# disqus:
#   id: disqusid
